package com.candikrush.dto;

public enum CKUserPermissions {
    CP_READ_UNPROCESSED, CP_READ_PROCESSED, CP_DELETE_UNPROCESSED, CP_DELETE_PROCESSED, CP_CREATE, APPROVE_CONTENT, EDIT_CONTENT, DELETE_CONTENT, CREATE_PACKAGE, EDIT_PACKAGE, DELETE_PACKAGE, CREATE_ACCOUNT, DELETE_ACCOUNT, EDIT_ACCOUNT_PERMISSIONS, CREATE_ROLE, EDIT_ROLE, DELETE_ROLE, UPDATE_API;
}
